services:
  inkscape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firestorm
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#    volumes:
#      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
#    devices:
#      - "/dev/kfd"
#      - "/dev/dri"
